### ISSUE TITLE
question about booster training and inference

### ISSUE THREAD

**Issue by jiaw-z** [jiaxiZeng/Parameterized-Cost-Volume-for-Stereo-Matching#1]
Hello, thanks for the shared code and checkpoint.
I am amazed by the great performance on the Booster dataset.
Can you provide more implementation details of training the pre-trained checkpoint on Booster.
I also find in the evaluation code, the booster images are downsampled by a scale of 2. While the paper shows it predicts disparities in the original resolution.
And is there any plan to make the booster checkpoint available?

**Comment by jiaxiZeng** [comment]
I appreciate your interest in our work. 
We follow the training strategy of crestereo, augmenting the booster dataset with the crestereo dataset to train the model for 13k steps based on the pre-trained model on sceneflow. Furthermore, we individually fine-tune the model on the booster dataset for 3k steps to get the final model. 
We are sorry for the inaccurate description of the booster's settings. In fact, the 1/4 output is used to initialize the model at 1/2 resolution.
As for the checkpoint, the code version for benchmark submission is a little different from our final version in github.  You can now download the checkpoint at [here]( https://www.dropbox.com/scl/fi/p18cibhpe3787p3d6bv6j/pcvnet_booster_sigma8_final.pth?rlkey=azr2t90jim0h0qrvwl1z9bg7r&dl=0) and validate the booster dataset using the booster's branch code.  Alternatively, you can retrain the model based on our latest version.

**Comment by jiaw-z** [comment]
Thanks for your helpful reply.
If I want to use the cascade inference for submission, do I need to upsample the 1/2 resolution results to full resolution?
And are the weights pre-trained on the augmented booster with crestereo available? I need some help to figure out how to train models and make inference on booster dataset.
